{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "dropshipping.namespace" . }}
  labels:
    {{- include "dropshipping.labels" . | nindent 4 }}
{{- end }}
