{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dropshipping.fullname" . }}-redis
  namespace: {{ include "dropshipping.namespace" . }}
  labels:
    {{- include "dropshipping.componentLabels" (dict "root" . "component" "redis") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: tcp-redis
      port: {{ .Values.global.redis.port }}
      targetPort: tcp-redis
      protocol: TCP
  selector:
    {{- include "dropshipping.selectorLabels" (dict "root" . "component" "redis") | nindent 4 }}
{{- end }}
